### ISSUE TITLE
NIRCam example notebook error

### ISSUE THREAD

**Issue by aliciacanipe** [spacetelescope/pandeia-coronagraphy#11]
I was hoping to use one of the example notebooks (nircam_photon_noise_and_contrast.ipynb) to create a slope image, but I think there might have been an update to the pandeia engine that is causing an error in the notebook now. The error is below. Is there any way I could get an updated example notebook? I can't figure out a workaround for the geometries error because I don't know what the original code looked like. 

`---------------------------------------------------------------------------
RemoteTraceback                           Traceback (most recent call last)
RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/Users/acanipe/miniconda3/envs/astroconda/lib/python3.5/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/Users/acanipe/miniconda3/envs/astroconda/lib/python3.5/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/Users/acanipe/miniconda3/envs/astroconda/lib/python3.5/site-packages/pandeia_coronagraphy/engine.py", line 96, in perform_calculation
    results = pandeia_calculation(calcfile)
  File "/Users/acanipe/miniconda3/envs/astroconda/lib/python3.5/site-packages/pandeia/engine/perform_calculation.py", line 39, in perform_calculation
    report = calculate_sn(calc_input, webapp=webapp)
  File "/Users/acanipe/miniconda3/envs/astroconda/lib/python3.5/site-packages/pandeia/engine/etc3D.py", line 1230, in calculate_sn
    scene = Scene(input=scene_configuration, webapp=webapp)
  File "/Users/acanipe/miniconda3/envs/astroconda/lib/python3.5/site-packages/pandeia/engine/scene.py", line 54, in __init__
    self._from_list(input)
  File "/Users/acanipe/miniconda3/envs/astroconda/lib/python3.5/site-packages/pandeia/engine/scene.py", line 91, in _from_list
    self.sources.append(src.Source(config=s, webapp=self.webapp))
  File "/Users/acanipe/miniconda3/envs/astroconda/lib/python3.5/site-packages/pandeia/engine/source.py", line 223, in __init__
    if self.shape['geometry'] in self.geometries:
AttributeError: 'Source' object has no attribute 'geometries'
"""

The above exception was the direct cause of the following exception:

AttributeError                            Traceback (most recent call last)
<ipython-input-10-beaa151e0cb1> in <module>()
      1 engine.options.wave_sampling = 20
----> 2 targ_results, ref_results = engine.calculate_batch([target,reference])

~/miniconda3/envs/astroconda/lib/python3.5/site-packages/pandeia_coronagraphy/engine.py in calculate_batch(calcfiles, nprocesses)
     66         nprocesses = mp.cpu_count()
     67     pool = mp.Pool(processes = nprocesses)
---> 68     results = pool.map(perform_calculation, calcfiles)
     69     pool.close()
     70     pool.join()

~/miniconda3/envs/astroconda/lib/python3.5/multiprocessing/pool.py in map(self, func, iterable, chunksize)
    264         in a list that is returned.
    265         '''
--> 266         return self._map_async(func, iterable, mapstar, chunksize).get()
    267 
    268     def starmap(self, func, iterable, chunksize=None):

~/miniconda3/envs/astroconda/lib/python3.5/multiprocessing/pool.py in get(self, timeout)
    642             return self._value
    643         else:
--> 644             raise self._value
    645 
    646     def _set(self, i, obj):

AttributeError: 'Source' object has no attribute 'geometries'`

Thanks for the help!
Alicia

**Comment by mperrin** [comment]
Hi Alicia, 

Yes, there are known issues/incompatibilities with recent version of Pandeia. Brian York has been working on fixes for these, in another branch of this codebase. There's a bunch of JIRA items in the MESA JIRA space related to this. 

(Apologies for brief response for now  - but wanted to let you know yes this is a known problem and is being worked on.)
